config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :expenses

  validates :name, presence: true
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_category, only: %i[index show new edit update create destroy]
  load_and_authorize_resource

  # GET /expenses or /expenses.json
  def index
    @expenses = @category.expenses
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @expense.category_ids << @category.id
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    respond_to do |format|
      if @expense.save
        format.html { redirect_to category_url(@category), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to category_url(@category), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to category_url(@category), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, category_ids: []).with_defaults(user_id: current_user.id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div class="expense-card" id="<%= dom_id expense %>">
  <div class="expense-details">
  <div>
    <p>
      <%= expense.name %>
    </p>
    <p class="date">
      <%= expense.created_at.strftime("%e %b %y") %>
    </p>
  </div>

  <p>
    <strong><%= number_to_currency(expense.amount) %></strong>
    
  </p>

  </div>
  <div class="edit-destroy-buttons">
    <%= link_to image_tag("edit.png"), edit_category_expense_path(@category, expense), class: 'edit-btn' %>
    <%= button_to image_tag("delete.png"), category_expense_path(@category, expense), method: :delete, class: 'delete-btn' %>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: [@category, expense]) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, autocomplete: "name", placeholder: "Name", class: "expense-name" %>
  </div>

  <div>
    <%= form.text_field :amount, autocomplete: "amount", placeholder: "Amount", class: "expense-amount" %>
  </div>

  <div>
    <h4>Select a category or categories</h4>
    <%#= form.label :categories, style: "display: block" %>
    <div class="checkbox-list">
    <%= form.collection_check_boxes :category_ids, Category.where(user_id: current_user.id), :id, :name_with_emoji do |b| %>
      <%= b.label class:"label-checkbox" do%>
         <%=b.check_box + b.text%>
        <%end%>
    <% end %>
    </div>
  </div>

  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="category-form">

<%= render "layouts/header_back_expenses", title: 'EDITING EXPENSE' %>

<%= render "form", expense: @expense %>

</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
  <% if can? :manage, expense %>
      <%= render expense %>
      <p>
        <%= link_to "Show this expense", category_expense_path(@category,expense) %>
      </p>
    <% end %>
  <% end %>
</div>

<%= link_to "New expense", new_category_expense_path %>

app/views/expenses/new.html.erb
<div class="category-form">

<%= render "layouts/header_back_expenses", title: 'NEW EXPENSE' %>

<%= render "form", expense: @expense %>

</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_category_expense_path(@category, @expense) %>
  <%= link_to "Back to expenses", category_expenses_path(@category) %>

  <%= button_to "Destroy this expense", category_expense_path(@category,@expense), method: :delete %>
</div>