config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :expenses
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#home"
end

app/views/layouts/_header.html.erb
<div class="header">
  <%= link_to "javascript:history.back()" do%>
    <%= image_tag ("/assets/back.png"), class: "back-img"%>
  <% end %>
  <p><%= title %></p>
  <p></p>
</div>

app/views/layouts/_header2.html.erb
<div class="header">
  <%= image_tag ("/assets/hamburger.png"), class: "hamburger-img"%>
  <p><%= title %></p>
  <p></p>
</div>

app/views/layouts/_header_back_categories.html.erb
<div class="header">
  <%= link_to categories_path do%>
    <%= image_tag ("/assets/back.png"), class: "back-img"%>
  <% end %>
  <p><%= title %></p>
  <p></p>
</div>

app/views/layouts/_header_back_expenses.html.erb
<div class="header">
  <%= link_to category_path(@category) do%>
    <%= image_tag ("/assets/back.png"), class: "back-img"%>
  <% end %>
  <p><%= title %></p>
  <p></p>
</div>

app/views/layouts/_header_hamburger.html.erb
<div class="header">
  <p></p><%#= image_tag ("/assets/hamburger.png"), class: "hamburger-img"%>
  <p><%= title %></p>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-logout-btn'  %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <h1>GoBudget</h1>

  <ul>
    <li class="nav-link"><%= link_to 'Categories', categories_path%></li>
   
    <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'sign-out' %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>